language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: IsYdZs4zfVexch6tQig6tiwuYvzNZz0QgATlNmQ5QLVFL2A3v0fIjoZp+wPV8MElsWw0pc+1GdJxXg2xd9n+gkrDMqBDFhksVoZ3zbIHPsPRO99PJ/9crvCEi4g4pFRPURLHV9Ko9Wp6VCs42s4dsrj4pDTXvKd8dolzf2mh+L2oCZUZa1Pr9sgX6O6pdrJ2XCpieTCppi2aOFGwz4ZqzmaocDSPxOHWwyz2zXPA0HTi6agbJ0HoUyDWmYfGXCInZCr0Ny9elqSU5nSWdx+XPxuX0tEpqunGYWM+1zF93iuJ+J+w9z2QoJZnDqQ+2o2Cr88gQ8Hby4ayO21MNgygDeMwy1krNc+Z+gM7rFDTmVfNQDv7QhX1A7bfUcOcEti3jINvprTOXh6b4QY7k3FeM0nlIP4mUBvw0CREwKYbM5qJfuO04Mm3LORpTi9dEtht4ZY+aAaZSHz+e1sUiQTlTAEjUVaIAPoNInxv91687pAhUAbKQMJadcyTpynpkJ57I2DVdh78LWc8dovFuxp7+NYrkP4xeKVUAyBJ3kFYLo4LpuvHhGuSsLLnW+EflDT9MzHQLHEG+hSJv3S3S6bhggSCBu9+Rh7D8TMYWxeXD2Wg/p1C9SO+ZXERi/8+1YKGVDiDIS1nyhCB48qFrx+6N8hMwD6ztCDTkm40HaT3j64=
script:
- nohup yarn test
